# Generated by Django 6.0.2 on 2026-02-08 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del cliente o empresa', max_length=150)),
                ('contact_email', models.EmailField(help_text='Correo de contacto del cliente', max_length=254)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Rol dentro del proyecto (ej: Dev, PM, QA)', max_length=100)),
                ('assigned_hours', models.PositiveIntegerField(help_text='Horas asignadas al proyecto')),
                ('assigned_at', models.DateField(auto_now_add=True, help_text='Fecha de incorporación al proyecto')),
                ('collaborator', models.ForeignKey(help_text='Usuario asignado al proyecto', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Cargo profesional (ej: Backend Developer, PM, QA)', max_length=100)),
                ('seniority', models.CharField(choices=[('JR', 'Junior'), ('MID', 'Mid'), ('SR', 'Senior'), ('LEAD', 'Lead')], help_text='Nivel de seniority', max_length=50)),
                ('user', models.OneToOneField(help_text='Usuario base del sistema', on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proyecto', max_length=200)),
                ('start_date', models.DateField(help_text='Fecha de inicio del proyecto')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de término del proyecto', null=True)),
                ('client', models.ForeignKey(help_text='Cliente dueño del proyecto (uno a muchos)', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project_management.client')),
                ('collaborators', models.ManyToManyField(help_text='Colaboradores asignados al proyecto', related_name='projects', through='project_management.Assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(help_text='Proyecto asignado', on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('project', 'collaborator')},
        ),
    ]
